version: 2.1

executors:
  diab-android-executor:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: "-Xmx1024m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb
    working_directory: ~/diab

jobs:
  build:
    executor: diab-android-executor
    steps:
      - checkout
      - run:
          name: Download deps
          command: ./gradlew dependencies
      - run:
          name: Assemble, lint and unit tests
          command: ./gradlew check -PisCiBuild
      # Store report results
      - store_artifacts:
          path: app/build/reports
          destination: app-reports
      # Save build dir
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

