version: 2

references:
    cache_key: &cache_key
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
    build:
        working_directory: ~/code
        docker:
            - image: circleci/android:api-28-alpha
        environment:
            JVM_OPTS: "-Xmx1024m"
            GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
            TERM: dumb
        steps:
            - checkout
            - restore_cache:
                <<: *cache_key
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - save_cache:
                <<: *cache_key
                paths:
                    - ~/.gradle/caches
                    - ~/.gradle/wrapper
            - run:
                name: JVM tests and Lint
                command: ./gradlew check -PisCiBuild
            - store_artifacts:
                path: app/build/reports
                destination: app-reports
            - store_artifacts:
                path: core/build/reports
                destination: core-reports
            - store_artifacts:
                path: export/build/reports
                destination: export-reports
            - store_artifacts:
                path: glucose/build/reports
                destination: glucose-reports
            - store_artifacts:
                path: insulin/build/reports
                destination: insulin-reports
            - store_artifacts:
                path: settings/build/reports
                destination: settings-reports
            - store_test_results:
                path: app/build/test-results
            - store_test_results:
                path: core/build/test-results
            - store_test_results:
                path: glucose/build/test-results
